name: kdb
description: KDB+ (kx.com) driver
version: 0.1.0
homepage: https://github.com/sannysanoff/dart-kdb
author: Sanny Sanoff <san@sysdate.com>

environment:
  sdk: '>=1.20.1'

dependencies:

dev_dependencies:
  test: ^0.12.0
